### ISSUE TITLE
UI v1 Release

### ISSUE THREAD

**Issue by jacogr** [ethcore/parity#2352]
Listing relevant issues that are open and needs to be addressed for the first release (assuming a very short timeframe):

Enhancements/Features -
- [ ] User token deployment - https://github.com/ethcore/parity/issues/2124
- [x] Signer auto popup on new tx - https://github.com/ethcore/parity/issues/2338
- [x] Auto Signer setup - https://github.com/ethcore/parity/issues/2135
- [x] Detect Signer issues & prompt for token - https://github.com/ethcore/parity/issues/2293
- [ ] Password hints - https://github.com/ethcore/parity/issues/2150
- [ ] Background selection - https://github.com/ethcore/parity/issues/2278
- [ ] Basic semantic analysis - https://github.com/ethcore/parity/issues/2280
- [ ] Import brain phrase - https://github.com/ethcore/parity/issues/2146 (easy)

Bugs -
- [x] Signer recent tx on top - https://github.com/ethcore/parity/issues/2343
- [ ] Possible FirstRun issues - https://github.com/ethcore/parity/issues/2330
- [ ] Transaction extradata not working - https://github.com/ethcore/parity/issues/2140

Other -
- [x] Build JS files on CI - https://github.com/ethcore/parity/issues/2346
- [x] Bundle fonts - https://github.com/ethcore/parity/issues/2344
- [x] Serve new UI from Parity - https://github.com/ethcore/parity/issues/2155

**Comment by jacogr** [comment]
Column added to Project.
