### ISSUE TITLE
Vaults

### ISSUE THREAD

**Issue by gavofyork** [ethcore/parity#3501]
Vaults are sub-directories of the main key directory. They contain JSON wallet files as normal, but these files do not contain fields problematic for privacy such as `address`, `meta` and `name`. Instead, this data is expressed as a separate, isolated, JSON dump (`{ address: "...", meta: "...", name: "..." }`) and the AES encrypted form of this dump is stored in the file. This is arranged as an additional field: `metacrypto` which takes the same form as `"crypto"`.

It is assumed that all JSON files in the same path will have the same vault password. Changes of password to vaults should happen on the entire directory. Vault secrets will be stored whenever vaults are opened. A vault being opened is application-wide, and keys are visible to all signer-privileged RPC clients.

Internal APIs to load all wallet files in a vault (providing a password), unloading all such wallet files, and change passwords of such wallet files, should be provided.

### JSONRPC

There should be additional, protected, RPCs:
- `parity_newVault(name, password)`
- `parity_openVault(name, password)`
- `parity_closeVault(name)`
- `parity_changeVaultPassword(name, new)`
- `parity_changeVault(address, newVault)`

Address meta data (for the `parity_getAddressMeta` RPC) should include an additional (automatically populated) `vault` field.

### Referring to vaults

No vault/root directory (i.e. how all keys are currently stored) should be referred to with the `null` value in JSON RPC/JS and `None` in Rust-land.

### Tasks

- [x] Internal APIs for creating new vaults & keys therein and loading/saving;
- [x] Internal APIs for changing vault password;
- [x] Internal APIs for moving keys;
- [x] RPC additions and changes;
- [x] Parity Wallet integration;

**Comment by jacogr** [comment]
With accounts/addresses we have some additional meta information associated with entries. We use this meta to store things like password hint, extended description and tags. In the case of Vaults at least the extended description and password hint would be beneficial.

One other thing to keep in mind for alignment, with account change passwords we take in the old as well as the new passwords, consistency here could be good.

**Comment by svyatonik** [comment]
@jacogr So you're suggesting to add something like `parity_setVaultMeta` && `parity_getVaultMeta`? Please confirm and I'll add these methods.
As for asking for the old password - as I understand, @gavofyork wanted to avoid unnecessary user interaction. Here is the comment:
https://github.com/ethcore/parity/pull/4366#issuecomment-276345089
So as I understand opening vault = unlocking vault data (!= unlocking vault accounts) until it will be closed.

**Comment by jacogr** [comment]
I'm 100% in agreement with the general sentiment of not making the user type in passwords all of the time, however don't believe that "changing the password" happens often enough that the password verification would get in the way. (Just adds slightly more friction to this one operation, but also some more "trust" that you are the original owner.) However, I can live with the current implementation.

Yes, I'm suggesting the `parity_setVaultMeta` && `parity_getVaultMeta` functions - at this point will just store the optional password hints & optional extended description in there. (It does add some flexibility is we feel to need to have slightly more info attached going forward as well).

**Comment by gavofyork** [comment]
@jacogr these RPCs are considered "secure", which means it's the UI's responsibility to provide any security requirements over and above those strictly necessary. if it is deemed sensible to require the user enter the old password to change to a new password (and i would probably agree), then the right place to do that is in the UI.
