### ISSUE TITLE
Address entry & display components should use Registry

### ISSUE THREAD

**Issue by gavofyork** [ethcore/parity#3991]
- [x] Address display component should display the Registered reverse name for an address, if it exists. – #4033
- [x] Address ~~entry~~ selector should be able to be given a Registry entry and resolve into an address. – #3992 
- [x] Address ~~entry~~ selector should autocomplete addresses to reverse names – #4066
- [x] Address selector component should be able to be given an email address registered with the EmailCertifier and decode into an address. – #3992

Some time soon:

- Address selector should autocomplete names to addresses – #4096

**Comment by rphmeier** [comment]
> Address display component should display the Registered name for an address
If it's in the address book with a different local name then that should be displayed either in place of it or together (but larger -- the user gave a specific name for a reason)

**Comment by gavofyork** [comment]
sure.

**Comment by ngotchac** [comment]
> Address entry should be able to be given a Registry entry and resolve into an address.

This is #3871 right?

**Comment by derhuerst** [comment]
So after some misunderstandings, the address selector now autocompletes:

- partially typed names from `ReverseConfirmed`
- partially typed addresses from `ReverseConfirmed`
- names & addresses from accounts, address book (contacts) & contracts

It looks up on an exact match

- registry `A` entry of a fully typed name
- address of a full typed, verified email address
